import { House, MousePointer2, Star, ToggleLeft, TextCursorInput, SquareCheck, CircleDot, ListFilter, AlignLeft, PanelTop, MessageSquare, PanelsTopLeft, Tag, Minus, Menu, SlidersHorizontal, TriangleAlert, Bell, ChevronsUpDown, CircleAlert, CircleUserRound, RectangleHorizontal, Keyboard, Ellipsis, Gauge, Columns3, ScanLine, SlidersVertical, LoaderCircle, TextSearch, PanelRight, Table, ChevronRight, Hash, Bold, Inbox, Command, CalendarDays, Tags, Upload, RectangleEllipsis, Copy, Link2, ChevronDown, List, IdCard, MousePointerClick, ListOrdered, PanelLeft, GalleryHorizontal, GripVertical, Group, CalendarRange, Clock, Network, History, Palette, ScrollText, Ratio, KeyRound, Search, ListPlus, PencilLine, Rows3, Wrench, Megaphone, Bookmark, Users, Code, Paintbrush, LayoutDashboard, UserCog, Mail, ChartLine, ChartColumn, ChartPie, ChartBar, Activity, TrendingUp, ShoppingCart, SquareKanban, LogIn, BadgeDollarSign, QrCode as QrCodeIcon, CreditCard as CreditCardIcon, WalletCards } from 'lucide-react'

const icon = (Icon: typeof House) => <Icon strokeWidth={1.5} />

export const groups = [
  { label: 'Overview', items: [
    { href: '/', label: 'Home', icon: icon(House) },
    { href: '/theme-studio', label: 'Theme studio', icon: icon(Paintbrush) },
  ] },
  { label: 'Examples', items: [
    { href: '/examples/dashboard', label: 'Dashboard', icon: icon(LayoutDashboard) },
    { href: '/examples/settings', label: 'Settings', icon: icon(UserCog) },
    { href: '/examples/inbox', label: 'Inbox', icon: icon(Mail) },
    { href: '/examples/checkout', label: 'Checkout', icon: icon(ShoppingCart) },
    { href: '/examples/board', label: 'Project board', icon: icon(SquareKanban) },
    { href: '/examples/auth', label: 'Authentication', icon: icon(LogIn) },
    { href: '/examples/pricing', label: 'Pricing', icon: icon(BadgeDollarSign) },
  ] },
  { label: 'Actions', items: [
    { href: '/button', label: 'Button', icon: icon(MousePointer2) },
    { href: '/icon-button', label: 'IconButton', icon: icon(Star) },
    { href: '/button-group', label: 'ButtonGroup', icon: icon(Group) },
    { href: '/copy-button', label: 'CopyButton', icon: icon(Copy) },
    { href: '/toggle', label: 'Toggle', icon: icon(Bold) },
    { href: '/dropdown-menu', label: 'DropdownMenu', icon: icon(Menu) },
    { href: '/context-menu', label: 'ContextMenu', icon: icon(MousePointerClick) },
    { href: '/command-palette', label: 'CommandPalette', icon: icon(Command) },
    { href: '/toolbar', label: 'Toolbar', icon: icon(Wrench) },
  ] },
  { label: 'Inputs', items: [
    { href: '/text-field', label: 'TextField', icon: icon(TextCursorInput) },
    { href: '/textarea', label: 'Textarea', icon: icon(AlignLeft) },
    { href: '/password-field', label: 'PasswordField', icon: icon(KeyRound) },
    { href: '/search-field', label: 'SearchField', icon: icon(Search) },
    { href: '/inline-edit', label: 'InlineEdit', icon: icon(PencilLine) },
    { href: '/number-field', label: 'NumberField', icon: icon(Hash) },
    { href: '/otp-input', label: 'OtpInput', icon: icon(RectangleEllipsis) },
    { href: '/select', label: 'Select', icon: icon(ListFilter) },
    { href: '/combobox', label: 'Combobox', icon: icon(TextSearch) },
    { href: '/multi-select', label: 'MultiSelect', icon: icon(Tags) },
    { href: '/tag-input', label: 'TagInput', icon: icon(ListPlus) },
    { href: '/date-picker', label: 'DatePicker', icon: icon(CalendarDays) },
    { href: '/credit-card-field', label: 'CreditCardField', icon: icon(WalletCards) },
    { href: '/date-range-picker', label: 'DateRangePicker', icon: icon(CalendarRange) },
    { href: '/time-picker', label: 'TimePicker', icon: icon(Clock) },
    { href: '/file-upload', label: 'FileUpload', icon: icon(Upload) },
    { href: '/checkbox', label: 'Checkbox', icon: icon(SquareCheck) },
    { href: '/radio-group', label: 'RadioGroup', icon: icon(CircleDot) },
    { href: '/switch', label: 'Switch', icon: icon(ToggleLeft) },
    { href: '/slider', label: 'Slider', icon: icon(SlidersVertical) },
    { href: '/range-slider', label: 'RangeSlider', icon: icon(SlidersHorizontal) },
    { href: '/segmented-control', label: 'SegmentedControl', icon: icon(Columns3) },
    { href: '/rating', label: 'Rating', icon: icon(Star) },
    { href: '/color-picker', label: 'ColorPicker', icon: icon(Palette) },
    { href: '/fieldset', label: 'Fieldset', icon: icon(Rows3) },
  ] },
  { label: 'Overlays', items: [
    { href: '/dialog', label: 'Dialog', icon: icon(PanelTop) },
    { href: '/alert-dialog', label: 'AlertDialog', icon: icon(TriangleAlert) },
    { href: '/sheet', label: 'Sheet', icon: icon(PanelRight) },
    { href: '/popover', label: 'Popover', icon: icon(SlidersHorizontal) },
    { href: '/tooltip', label: 'Tooltip', icon: icon(MessageSquare) },
    { href: '/hover-card', label: 'HoverCard', icon: icon(IdCard) },
  ] },
  { label: 'Feedback', items: [
    { href: '/alert', label: 'Alert', icon: icon(CircleAlert) },
    { href: '/banner', label: 'Banner', icon: icon(Megaphone) },
    { href: '/toast', label: 'Toast', icon: icon(Bell) },
    { href: '/progress', label: 'Progress', icon: icon(Gauge) },
    { href: '/spinner', label: 'Spinner', icon: icon(LoaderCircle) },
    { href: '/skeleton', label: 'Skeleton', icon: icon(ScanLine) },
    { href: '/empty-state', label: 'EmptyState', icon: icon(Inbox) },
  ] },
  { label: 'Navigation', items: [
    { href: '/sidebar', label: 'Sidebar', icon: icon(PanelLeft) },
    { href: '/tabs', label: 'Tabs', icon: icon(PanelsTopLeft) },
    { href: '/breadcrumb', label: 'Breadcrumb', icon: icon(ChevronRight) },
    { href: '/pagination', label: 'Pagination', icon: icon(Ellipsis) },
    { href: '/stepper', label: 'Stepper', icon: icon(ListOrdered) },
    { href: '/link', label: 'Link', icon: icon(Link2) },
    { href: '/accordion', label: 'Accordion', icon: icon(ChevronsUpDown) },
  ] },
  { label: 'Charts', items: [
    { href: '/line-chart', label: 'LineChart', icon: icon(ChartLine) },
    { href: '/bar-chart', label: 'BarChart', icon: icon(ChartColumn) },
    { href: '/donut-chart', label: 'DonutChart', icon: icon(ChartPie) },
    { href: '/bar-list', label: 'BarList', icon: icon(ChartBar) },
    { href: '/sparkline', label: 'Sparkline', icon: icon(Activity) },
    { href: '/stat', label: 'Stat', icon: icon(TrendingUp) },
  ] },
  { label: 'Layout', items: [
    { href: '/card', label: 'Card', icon: icon(RectangleHorizontal) },
    { href: '/collapsible', label: 'Collapsible', icon: icon(ChevronDown) },
    { href: '/resizable', label: 'Resizable', icon: icon(GripVertical) },
    { href: '/scroll-area', label: 'ScrollArea', icon: icon(ScrollText) },
    { href: '/aspect-ratio', label: 'AspectRatio', icon: icon(Ratio) },
    { href: '/separator', label: 'Separator', icon: icon(Minus) },
  ] },
  { label: 'Display', items: [
    { href: '/table', label: 'Table', icon: icon(Table) },
    { href: '/description-list', label: 'DescriptionList', icon: icon(List) },
    { href: '/tree-view', label: 'TreeView', icon: icon(Network) },
    { href: '/timeline', label: 'Timeline', icon: icon(History) },
    { href: '/carousel', label: 'Carousel', icon: icon(GalleryHorizontal) },
    { href: '/avatar', label: 'Avatar', icon: icon(CircleUserRound) },
    { href: '/avatar-group', label: 'AvatarGroup', icon: icon(Users) },
    { href: '/badge', label: 'Badge', icon: icon(Tag) },
    { href: '/tag', label: 'Tag', icon: icon(Bookmark) },
    { href: '/code-block', label: 'CodeBlock', icon: icon(Code) },
    { href: '/kbd', label: 'Kbd', icon: icon(Keyboard) },
    { href: '/qr-code', label: 'QrCode', icon: icon(QrCodeIcon) },
    { href: '/credit-card', label: 'CreditCard', icon: icon(CreditCardIcon) },
  ] },
]
